-- If table already exists, remove
drop table if exists bookmarks;

-- Create the new table
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT,
  rating NUMERIC DEFAULT 0
);

-- Insert data
insert into bookmarks (title, url)
values 
  ('Google', 'https://www.google.com'),
  ('Google', 'https://www.google.com'),
  ('Google', 'https://www.google.com'),
  ('Google', 'https://www.google.com'),
  ('Google', 'https://www.google.com'),
  ('Google', 'https://www.google.com'),
  ('Google', 'https://www.google.com'),
  ('Google', 'https://www.google.com'),
  ('Google', 'https://www.google.com'),
  ('Google', 'https://www.google.com'),
  ('Google', 'https://www.google.com'),
  ('Google', 'https://www.google.com');